[package]
name = "datavis"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.28"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
anyhow = "1.0"
egui_plot = "0.28"
rustfft = "6"
serde_json = "1"
egui_tiles = { version = "0.9", features = ["serde"] }
zmq = "0.10"
prost-reflect = "0.14"
protox = "0.7"
mcap = "0.8"
rfd = "0.14"
crossbeam-channel = "0.5"
prost-types = "0.13"
rumqttc = "0.24"
boxcar = "0.2.14"
egui-phosphor = "0.6"

[dev-dependencies]
tempfile = "3"
