default_window_s = 10.0

[screens.main]
tiles_json = '{"id":5410085660609570307,"root":1,"tiles":{"next_tile_id":2,"tiles":{"1":{"Pane":0}},"invisible":[]},"height":null,"width":null}'

[[screens.main.panels]]
type = "waveform"
channels = []
cursors = false
dots = false
