[screens.analysis]
tiles_json = '{"id":3063161388594286623,"root":4,"tiles":{"next_tile_id":5,"tiles":{"2":{"Pane":1},"3":{"Pane":2},"1":{"Pane":0},"4":{"Container":{"Grid":{"children":[1,2,3],"layout":"Auto","col_shares":[1.0],"row_shares":[1.0,1.0,1.0]}}}},"invisible":[]},"height":null,"width":null}'

[[screens.analysis.panels]]
type = "spectrum"
channel = "example/demo/sine"
fft_size = 1024
window = "hann"

[[screens.analysis.panels]]
type = "xy_scatter"
time_window_s = 2.0
x_channel = "example/demo/sine"
y_channel = "example/demo/counter"

[[screens.analysis.panels]]
type = "gauge"
channel = "example/demo/log"
max = 100.0
min = 0.0

[screens.main]
tiles_json = '{"id":5410085660609570307,"root":6,"tiles":{"next_tile_id":9,"tiles":{"2":{"Pane":1},"6":{"Container":{"Grid":{"children":[1,2,3,4,5,7,8],"layout":"Auto","col_shares":[1.0,1.0],"row_shares":[1.0,1.0,1.0,1.0]}}},"7":{"Pane":5},"1":{"Pane":0},"3":{"Pane":2},"4":{"Pane":3},"5":{"Pane":4},"8":{"Pane":6}},"invisible":[]},"height":null,"width":null}'

[[screens.main.panels]]
type = "waveform"
channels = ["example/demo/sine"]
cursors = true
time_window_s = 5.0

[[screens.main.panels]]
type = "gauge"
channel = "example/demo/sine"
max = 10.0
min = -10.0

[[screens.main.panels]]
type = "numeric"
channel = "example/demo/counter"

[[screens.main.panels]]
type = "state_graph"
channel = "example/demo/enabled"
time_window_s = 30.0

[screens.main.panels.states]
0 = "OFF"
1 = "ON"

[[screens.main.panels]]
type = "log"
channels = ["example/demo/log"]
max_lines = 200

[[screens.main.panels]]
type = "gauge"
channel = "example/demo/counter"
max = 100.0
min = 0.0

[[screens.main.panels]]
type = "waveform"
channels = ["example/demo/counter"]
cursors = false
time_window_s = 5.0
